
"""
Shipment-aware demo chatbot (no new ML pipeline).

Uses the existing risk assessment + alerts as context. If OPENAI_API_KEY is
set, the reply is generated by the OpenAI Chat Completions API via httpx.
Otherwise (or on API failure) a deterministic fallback is returned so the
local demo still answers from live data.
"""

from __future__ import annotations

from typing import Any

import httpx

from .. import crud
from ..config import get_settings
from . import risk as risk_service

settings = get_settings()

OPENAI_URL = "https://api.openai.com/v1/chat/completions"

PROJECT_OVERVIEW = (
    "ColdChain AI is a real-time cold-chain logistics monitoring and spoilage "
    "risk prediction system. IoT telemetry is ingested over MQTT into PostgreSQL. "
    "A cumulative exposure engine (Q10 ageing) tracks time and degree-minutes "
    "outside the product temperature range. XGBoost estimates spoilage risk, "
    "an LSTM forecasts temperature/humidity, an autoencoder flags sensor-pattern "
    "anomalies, a CNN classifies packaging condition from an uploaded image, "
    "and SHAP explains the XGBoost score. The displayed risk level blends the "
    "model score with rule-based exposure severity. Scores are demo/decision-"
    "support outputs, not calibrated medical or regulatory limits."
)


def compact_context(payload: dict[str, Any], alerts: list) -> dict[str, Any]:
    """Shrink a risk API payload into chatbot context (read-only numbers)."""
    exposure = payload.get("exposure") or {}
    latest = payload.get("latest_reading") or {}
    forecast = payload.get("lstm_forecast") or {}
    anomaly = payload.get("anomaly") or {}
    packaging = payload.get("packaging") or {}
    shipment = payload.get("shipment")
    product = payload.get("product")

    def _get(obj, name, default=None):
        if obj is None:
            return default
        if isinstance(obj, dict):
            return obj.get(name, default)
        return getattr(obj, name, default)

    recs = payload.get("recommendations") or []
    factors = payload.get("shap_top_factors") or []

    return {
        "project": PROJECT_OVERVIEW,
        "shipment_id": payload.get("shipment_id"),
        "vehicle_id": _get(shipment, "vehicle_id"),
        "origin": _get(shipment, "origin"),
        "destination": _get(shipment, "destination"),
        "status": _get(shipment, "status"),
        "product_name": _get(product, "name"),
        "allowed_temperature": [
            _get(product, "minimum_temperature"),
            _get(product, "maximum_temperature"),
        ],
        "risk_level": payload.get("risk_level"),
        "risk_percent": payload.get("risk_percent"),
        "risk_score": payload.get("risk_score"),
        "risk_reasons": payload.get("risk_reasons") or [],
        "model_risk_score": payload.get("model_risk_score"),
        "rule_based_score": payload.get("rule_based_score"),
        "latest_temperature": latest.get("temperature"),
        "latest_humidity": latest.get("humidity"),
        "latest_battery": latest.get("battery_level"),
        "door_open": latest.get("door_open"),
        "latitude": latest.get("latitude"),
        "longitude": latest.get("longitude"),
        "exposure_status": exposure.get("status"),
        "total_excursion_minutes": exposure.get("total_excursion_minutes"),
        "percent_readings_outside_range": exposure.get(
            "percent_readings_outside_range"
        ),
        "remaining_shelf_life_hours": payload.get("remaining_shelf_life_hours"),
        "equivalent_age_hours": exposure.get("equivalent_age_hours"),
        "lstm": {
            "status": forecast.get("status"),
            "detail": forecast.get("detail"),
            "predicted_breach": forecast.get("predicted_breach"),
        },
        "anomaly": {
            "status": anomaly.get("status"),
            "score": anomaly.get("score"),
            "threshold": anomaly.get("threshold"),
            "is_anomaly": anomaly.get("is_anomaly"),
            "detail": anomaly.get("detail"),
        },
        "packaging": {
            "status": packaging.get("status"),
            "predicted_class": packaging.get("predicted_class"),
            "confidence": packaging.get("confidence"),
            "detail": packaging.get("detail"),
        },
        "shap_top_factors": [
            {
                "feature": (
                    f.get("feature")
                    if isinstance(f, dict)
                    else getattr(f, "feature", None)
                ),
                "effect": (
                    f.get("effect")
                    if isinstance(f, dict)
                    else getattr(f, "effect", None)
                ),
                "shap_value": (
                    f.get("shap_value")
                    if isinstance(f, dict)
                    else getattr(f, "shap_value", None)
                ),
            }
            for f in factors[:8]
        ],
        "alerts": [
            {
                "type": getattr(a, "alert_type", None),
                "severity": getattr(a, "severity", None),
                "message": getattr(a, "message", None),
                "acknowledged": getattr(a, "acknowledged", None),
            }
            for a in (alerts or [])[:15]
        ],
        "recommendations": [
            {
                "code": (
                    r.get("code")
                    if isinstance(r, dict)
                    else getattr(r, "code", None)
                ),
                "severity": (
                    r.get("severity")
                    if isinstance(r, dict)
                    else getattr(r, "severity", None)
                ),
                "action": (
                    r.get("action")
                    if isinstance(r, dict)
                    else getattr(r, "action", None)
                ),
                "reason": (
                    r.get("reason")
                    if isinstance(r, dict)
                    else getattr(r, "reason", None)
                ),
            }
            for r in recs[:8]
        ],
        "disclaimer": payload.get("disclaimer"),
    }


def load_shipment_context(db, shipment_id: int) -> dict[str, Any] | None:
    """Read-only: existing assessment + alerts. Does not raise alerts or train."""
    shipment = crud.get_shipment(db, shipment_id)

    if shipment is None:
        return None

    product = crud.get_product(db, shipment.product_id)

    assessment = risk_service.assess_shipment(
        db,
        shipment,
        product=product,
        include_shap=True,
        use_cache=True,
        raise_alerts=False,
    )

    payload = risk_service.to_api_payload(assessment)

    alerts = crud.get_alerts_for_shipment(
        db,
        shipment_id,
        skip=0,
        limit=20,
    )

    return compact_context(payload, alerts)


def fallback_reply(message: str, context: dict[str, Any] | None) -> str:
    """Deterministic demo answers from live context when OpenAI is unavailable."""

    q = message.lower().strip()

    if context is None:
        return (
            "No shipment is selected. Open a shipment on the dashboard, or send "
            "shipment_id in the request, for live shipment information."
        )

    sid = context.get("shipment_id")

    # ---------------------------------------------------------
    # Specific field questions
    # ---------------------------------------------------------

    wants_location = any(
        phrase in q
        for phrase in (
            "location",
            "where is",
            "where's",
            "where are",
            "current location",
            "located",
            "position",
        )
    )

    wants_temperature = any(
        phrase in q
        for phrase in (
            "temperature",
            "temp",
            "current temp",
        )
    )

    wants_humidity = any(
        phrase in q
        for phrase in (
            "humidity",
            "humid",
        )
    )

    wants_battery = any(
        phrase in q
        for phrase in (
            "battery",
            "battery level",
            "power level",
        )
    )

    wants_status = any(
        phrase in q
        for phrase in (
            "status",
            "shipment status",
            "current status",
        )
    )

    # ---------------------------------------------------------
    # Existing detailed intents
    # ---------------------------------------------------------

    wants_risk = any(
        w in q
        for w in (
            "risk",
            "spoil",
            "score",
        )
    )

    wants_pack = any(
        w in q
        for w in (
            "packag",
            "cnn",
            "image",
            "seal",
            "crush",
        )
    )

    wants_anom = any(
        w in q
        for w in (
            "anomal",
            "autoencoder",
            "unusual",
        )
    )

    wants_rec = any(
        w in q
        for w in (
            "recommend",
            "action",
            "what should",
            "reroute",
        )
    )

    wants_alert = "alert" in q

    wants_lstm = any(
        w in q
        for w in (
            "forecast",
            "lstm",
            "predict",
        )
    )

    wants_shap = any(
        w in q
        for w in (
            "shap",
            "factor",
            "explain",
        )
    )

    wants_exp = any(
        w in q
        for w in (
            "expos",
            "shelf",
            "excursion",
            "expir",
        )
    )

    wants_general = any(
        w in q
        for w in (
            "what is coldchain",
            "what is cold chain",
            "this system",
            "project",
        )
    )

    wants_full_details = any(
        phrase in q
        for phrase in (
            "full details",
            "all details",
            "complete details",
            "entire shipment",
            "everything about",
            "show all",
            "give me details",
        )
    )

    # ---------------------------------------------------------
    # IMPORTANT:
    # Specific field questions return ONLY that field.
    # ---------------------------------------------------------

    if wants_location:
        origin = context.get("origin")
        destination = context.get("destination")
        latitude = context.get("latitude")
        longitude = context.get("longitude")

        location_parts = []

        if origin or destination:
            location_parts.append(
                f"Shipment {sid}: {origin or 'Unknown'} → {destination or 'Unknown'}."
            )

        if latitude is not None and longitude is not None:
            location_parts.append(
                f"Current coordinates: {latitude}, {longitude}."
            )

        if location_parts:
            return " ".join(location_parts)

        return f"Current location for Shipment {sid} is not available."

    if wants_temperature and not wants_risk:
        temp = context.get("latest_temperature")

        if temp is None:
            return f"Current temperature for Shipment {sid} is not available."

        return f"Shipment {sid} current temperature: {temp} °C."

    if wants_humidity and not wants_temperature:
        humidity = context.get("latest_humidity")

        if humidity is None:
            return f"Current humidity for Shipment {sid} is not available."

        return f"Shipment {sid} current humidity: {humidity}%."

    if wants_battery:
        battery = context.get("latest_battery")

        if battery is None:
            return f"Battery level for Shipment {sid} is not available."

        return f"Shipment {sid} battery level: {battery}%."

    if wants_status:
        status = context.get("status")

        if status is None:
            return f"Status for Shipment {sid} is not available."

        return f"Shipment {sid} status: {status}."

    # ---------------------------------------------------------
    # Full shipment details
    # ---------------------------------------------------------

    if wants_full_details:
        parts: list[str] = []

        parts.append(
            f"Shipment {sid} "
            f"({context.get('product_name') or 'unknown product'}, "
            f"{context.get('origin')} → {context.get('destination')}, "
            f"status {context.get('status')})."
        )

        parts.append(
            f"Latest temperature {context.get('latest_temperature')} °C, "
            f"humidity {context.get('latest_humidity')}%, "
            f"battery {context.get('latest_battery')}%."
        )

        parts.append(
            f"Risk level: {context.get('risk_level')} "
            f"({context.get('risk_percent')}% display score)."
        )

        parts.append(
            f"Exposure status: {context.get('exposure_status')}, "
            f"cumulative excursion: "
            f"{context.get('total_excursion_minutes')} minutes."
        )

        return "\n\n".join(parts)

    # ---------------------------------------------------------
    # Detailed existing responses
    # ---------------------------------------------------------

    specific = (
        wants_risk
        or wants_pack
        or wants_anom
        or wants_rec
        or wants_alert
        or wants_lstm
        or wants_shap
        or wants_exp
        or wants_temperature
        or wants_humidity
        or wants_battery
        or wants_status
        or wants_location
    )

    parts: list[str] = []

    if wants_general:
        parts.append(PROJECT_OVERVIEW)

    parts.append(
        f"Shipment {sid} "
        f"({context.get('product_name') or 'unknown product'}, "
        f"{context.get('origin')} → {context.get('destination')}, "
        f"status {context.get('status')})."
    )

    if wants_risk or not specific:
        level = context.get("risk_level")
        pct = context.get("risk_percent")

        parts.append(
            f"Risk level is {level}"
            + (f" ({pct}% display score)." if pct is not None else ".")
            + f" XGBoost model risk score: {context.get('model_risk_score')}; "
            f"rule-based score: {context.get('rule_based_score')}."
        )

        reasons = context.get("risk_reasons") or []

        if reasons:
            parts.append("Why: " + " ".join(reasons[:4]))

    if wants_temperature or wants_humidity or wants_exp or not specific:
        parts.append(
            f"Latest temperature {context.get('latest_temperature')} °C, "
            f"humidity {context.get('latest_humidity')}% "
            f"(allowed range {context.get('allowed_temperature')}). "
            f"Cumulative excursion "
            f"{context.get('total_excursion_minutes')} min "
            f"({context.get('percent_readings_outside_range')}% "
            f"of readings outside range); "
            f"exposure status {context.get('exposure_status')}. "
            f"Remaining shelf life "
            f"{context.get('remaining_shelf_life_hours')} h "
            f"after {context.get('equivalent_age_hours')} h "
            f"Q10-equivalent age."
        )

    if wants_lstm or not specific:
        lstm = context.get("lstm") or {}
        breach = lstm.get("predicted_breach")

        extra = f" Predicted breach: {breach}." if breach else ""

        parts.append(
            f"LSTM forecast status: {lstm.get('status')}."
            + (
                f" {lstm.get('detail')}"
                if lstm.get("detail")
                else ""
            )
            + extra
        )

    if wants_anom or not specific:
        an = context.get("anomaly") or {}

        parts.append(
            f"Autoencoder anomaly status: {an.get('status')} "
            f"(score {an.get('score')} vs threshold "
            f"{an.get('threshold')}; "
            f"is_anomaly={an.get('is_anomaly')})."
            + (
                f" {an.get('detail')}"
                if an.get("detail")
                else ""
            )
        )

    if wants_pack or not specific:
        pk = context.get("packaging") or {}

        if pk.get("predicted_class"):
            parts.append(
                f"CNN packaging condition: "
                f"{pk.get('predicted_class')} "
                f"(confidence {pk.get('confidence')}, "
                f"status {pk.get('status')})."
            )
        else:
            parts.append(
                f"CNN packaging status: {pk.get('status')}."
                + (
                    f" {pk.get('detail')}"
                    if pk.get("detail")
                    else ""
                )
            )

    if wants_shap:
        factors = context.get("shap_top_factors") or []

        if factors:
            bits = [
                f"{f.get('feature')} "
                f"({f.get('effect')}, {f.get('shap_value')})"
                for f in factors[:5]
            ]

            parts.append(
                "Top SHAP factors: " + "; ".join(bits) + "."
            )
        else:
            parts.append(
                "SHAP top factors are not available for this assessment."
            )

    if wants_alert or not specific:
        alerts = context.get("alerts") or []

        if not alerts:
            parts.append(
                "There are no persisted alerts for this shipment."
            )
        else:
            bits = [
                f"{a.get('type')} "
                f"[{a.get('severity')}]: "
                f"{a.get('message')}"
                for a in alerts[:5]
            ]

            parts.append(
                "Alerts: " + " | ".join(bits)
            )

    if wants_rec or not specific:
        recs = context.get("recommendations") or []

        if not recs:
            parts.append(
                "No recommendations are listed for this shipment."
            )
        else:
            bits = [
                f"{r.get('code')}: "
                f"{r.get('action')} "
                f"({r.get('reason')})"
                for r in recs[:5]
            ]

            parts.append(
                "Recommendations: " + " | ".join(bits)
            )

    if context.get("disclaimer"):
        parts.append(str(context["disclaimer"]))

    return "\n\n".join(parts)


def openai_reply(
    message: str,
    context: dict[str, Any] | None,
) -> str | None:
    """Call OpenAI; return None if the key is missing or the request fails."""

    key = (settings.openai_api_key or "").strip()

    if not key or key.startswith("your-openai"):
        return None

    import json

    system = (
        "You are the ColdChain AI operator assistant. "
        "Answer only from the provided CONTEXT and project description. "
        "Do not invent sensor readings or model scores. "
        "If a field is missing, say so. "
        "Be concise and answer ONLY what the user asks. "
        "If the user asks for one specific field such as location, "
        "temperature, humidity, battery, or status, return ONLY that field "
        "and do not provide unrelated shipment information. "
        "If the user asks for full details, provide the relevant shipment "
        "details. "
        "Risk scores are demo/decision-support outputs."
    )

    user = json.dumps(
        {
            "question": message,
            "context": context or {"project": PROJECT_OVERVIEW},
        }
    )

    try:
        response = httpx.post(
            OPENAI_URL,
            headers={
                "Authorization": f"Bearer {key}",
                "Content-Type": "application/json",
            },
            json={
                "model": settings.openai_model or "gpt-4o-mini",
                "temperature": 0.2,
                "max_tokens": 500,
                "messages": [
                    {
                        "role": "system",
                        "content": system,
                    },
                    {
                        "role": "user",
                        "content": user,
                    },
                ],
            },
            timeout=20.0,
        )

        response.raise_for_status()

        data = response.json()

        text = data["choices"][0]["message"]["content"]

        return (text or "").strip() or None

    except Exception as exc:
        print(
            f"[chat] OpenAI request failed; "
            f"using fallback ({exc})"
        )
        return None


def answer(
    db,
    message: str,
    shipment_id: int | None,
) -> dict[str, Any]:

    context = None

    if shipment_id is not None:
        context = load_shipment_context(
            db,
            shipment_id,
        )

        if context is None:
            return {"missing_shipment": True}

    # Handle specific field questions with the deterministic fallback
    # so the chatbot returns only the requested information.
    q = message.lower().strip()

    specific_field_question = any(
        phrase in q
        for phrase in (
            "location",
            "where is",
            "where's",
            "where are",
            "current location",
            "temperature",
            "temp",
            "humidity",
            "humid",
            "battery",
            "status",
        )
    )

    if specific_field_question:
        return {
            "reply": fallback_reply(
                message,
                context,
            ),
            "shipment_id": shipment_id,
            "source": "fallback",
        }

    # Use OpenAI for general questions when available.
    generated = openai_reply(
        message,
        context,
    )

    if generated:
        return {
            "reply": generated,
            "shipment_id": shipment_id,
            "source": "openai",
        }

    return {
        "reply": fallback_reply(
            message,
            context,
        ),
        "shipment_id": shipment_id,
        "source": "fallback",
    }