"""
Rule-based recommendation engine (Phase A, Step 5).

Every recommendation is RULE-BASED OUTPUT derived from the shipment's actual
conditions (cumulative exposure, latest readings, ML outputs). Nothing here is
generated by a language model, and none of it is a regulatory or medical
decision - the strings are decision *support* for an operator.

Item shape:
    {
      "code":       stable identifier (for UI grouping / tests),
      "severity":   "critical" | "warning" | "info",
      "priority":   1 (most urgent) .. 5,
      "reason":     why it was raised (includes the values it used),
      "action":     what the operator should do,
      "source":     "RULE-BASED",
      "evidence":   the numbers behind the rule,
    }

Rules and their conditions are documented in docs/step5.md.
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any, Sequence

from ..config import get_settings

settings = get_settings()

SEVERITY_ORDER = {"critical": 0, "warning": 1, "info": 2}

# Application thresholds used by the rules below (documented, not regulatory).
DOOR_OPEN_LOOKBACK_READINGS = 8
DOOR_OPEN_WARN_COUNT = 3
SHELF_LIFE_WARN_FRACTION = 0.75
def _item(
    code: str,
    severity: str,
    priority: int,
    reason: str,
    action: str,
    evidence: dict[str, Any] | None = None,
) -> dict[str, Any]:
    return {
        "code": code,
        "severity": severity,
        "priority": priority,
        "reason": reason,
        "action": action,
        "source": "RULE-BASED",
        "evidence": evidence or {},
    }


def _hours_until(moment) -> float | None:
    """Hours from now (UTC) to a (possibly naive/tz-aware) datetime."""
    if moment is None:
        return None
    if isinstance(moment, str):
        try:
            moment = datetime.fromisoformat(moment)
        except ValueError:
            return None
    now = datetime.now(timezone.utc)
    if moment.tzinfo is None:
        moment = moment.replace(tzinfo=timezone.utc)
    return (moment - now).total_seconds() / 3600.0
def build_recommendations(
    *,
    shipment,
    product,
    metrics: dict[str, Any] | None,
    risk_level: str,
    model_result: dict[str, Any] | None,
    anomaly: dict[str, Any] | None,
    forecast: dict[str, Any] | None,
    latest_reading=None,
    readings: Sequence = (),
) -> list[dict[str, Any]]:
    """
    Build the ordered recommendation list for one shipment.

    The function is pure: it only reads the values it is given, so it can be
    unit-tested without a database or any model artifact.
    """
    items: list[dict[str, Any]] = []
    metrics = metrics or {}
    model_result = model_result or {}
    anomaly = anomaly or {}
    forecast = forecast or {}

    if not metrics.get("total_readings"):
        items.append(_item(
            "NO_TELEMETRY",
            "info",
            3,
            "No telemetry readings are stored for this shipment yet.",
            "Confirm the sensor gateway publishes to MQTT and that the shipment id matches.",
            {"total_readings": 0},
        ))
        return items

    excursion_minutes = float(metrics.get("total_excursion_minutes") or 0.0)
    excursion_limit = float(metrics.get("excursion_limit_minutes") or 0.0)
    percent_outside = float(metrics.get("percent_readings_outside_range") or 0.0)
    remaining_shelf = float(metrics.get("remaining_shelf_life_hours") or 0.0)
    equivalent_age = float(metrics.get("equivalent_age_hours") or 0.0)
    shelf_total = remaining_shelf + equivalent_age
    shelf_used_fraction = (equivalent_age / shelf_total) if shelf_total > 0 else 0.0

    # -------------------------------------------------- cumulative exposure
    if excursion_limit > 0 and excursion_minutes > excursion_limit:
        items.append(_item(
            "EXCESSIVE_CUMULATIVE_EXPOSURE",
            "critical",
            1,
            (
                f"Cumulative time outside the allowed range is {excursion_minutes:.0f} min, above the "
                f"tolerated {excursion_limit:.0f} min ({percent_outside:.1f}% of readings outside range)."
            ),
            "Inspect the refrigeration unit now and prioritise this shipment for handling/verification.",
            {
                "total_excursion_minutes": excursion_minutes,
                "excursion_limit_minutes": excursion_limit,
                "percent_readings_outside_range": percent_outside,
            },
        ))
    elif excursion_minutes > 0:
        items.append(_item(
            "TEMPERATURE_EXCURSION",
            "warning",
            2,
            (
                f"{excursion_minutes:.0f} min of cumulative excursion detected (allowed "
                f"{excursion_limit:.0f} min); peak {metrics.get('max_temperature')} C vs maximum "
                f"{getattr(product, 'maximum_temperature', None)} C."
            ),
            "Inspect refrigeration and reduce door-open exposure so the exposure stops accumulating.",
            {
                "total_excursion_minutes": excursion_minutes,
                "excursion_limit_minutes": excursion_limit,
                "max_temperature": metrics.get("max_temperature"),
            },
        ))

    # ---------------------------------------------------- under-cooling check
    min_temp = metrics.get("min_temperature")
    product_min = float(getattr(product, "minimum_temperature", 0.0))
    if min_temp is not None and float(min_temp) < product_min:
        items.append(_item(
            "BELOW_MINIMUM_TEMPERATURE",
            "warning",
            2,
            f"Minimum observed temperature {float(min_temp):.2f} C is below the allowed minimum {product_min:.2f} C.",
            "Check temperature control settings - over-cooling/freezing can damage the load.",
            {"min_temperature": float(min_temp), "minimum_temperature": product_min},
        ))
    # ------------------------------------------------- MODEL OUTPUT driven rules
    model_score = model_result.get("risk_score")
    if risk_level in ("HIGH", "CRITICAL"):
        items.append(_item(
            "HIGH_MODEL_RISK",
            "critical" if risk_level == "CRITICAL" else "warning",
            1 if risk_level == "CRITICAL" else 2,
            (
                f"Blended risk level {risk_level}"
                + (f" (XGBoost risk score {model_score:.2f})." if model_score is not None else ".")
            ),
            "Prioritise shipment handling and verify the load at the next check point.",
            {"risk_level": risk_level, "model_risk_score": model_score},
        ))

    if anomaly.get("status") == "anomalous":
        items.append(_item(
            "ANOMALY_DETECTED",
            "warning",
            2,
            (
                f"Autoencoder anomaly score {anomaly.get('score')} exceeds its calibrated threshold "
                f"{anomaly.get('threshold')} (unusual temperature/humidity pattern)."
            ),
            "Inspect the refrigeration unit and the sensor calibration for the flagged window.",
            {"score": anomaly.get("score"), "threshold": anomaly.get("threshold")},
        ))

    breach = forecast.get("predicted_breach")
    if forecast.get("status") == "ok" and breach:
        items.append(_item(
            "FORECAST_TEMPERATURE_BREACH",
            "warning",
            2,
            (
                f"LSTM forecast predicts {str(breach.get('direction', '')).replace('_', ' ')} in about "
                f"{float(breach.get('minutes_ahead') or 0):.0f} min "
                f"({breach.get('predicted_temperature')} C)."
            ),
            "Check temperature control before the predicted breach and reduce door-open exposure.",
            dict(breach),
        ))
    # ------------------------------------------------------------ latest reading
    if latest_reading is not None:
        if bool(getattr(latest_reading, "door_open", False)):
            items.append(_item(
                "DOOR_OPEN_NOW",
                "warning",
                3,
                "The latest reading reports the container door as open.",
                "Reduce door-open exposure: close/secure the door and review loading procedures.",
                {"door_open": True},
            ))
        humidity = getattr(latest_reading, "humidity", None)
        product_max_h = float(getattr(product, "maximum_humidity", 100.0))
        product_min_h = float(getattr(product, "minimum_humidity", 0.0))
        if humidity is not None and (float(humidity) > product_max_h or float(humidity) < product_min_h):
            items.append(_item(
                "HUMIDITY_OUT_OF_RANGE",
                "warning",
                4,
                f"Humidity {float(humidity):.1f}% is outside the allowed {product_min_h:.0f}-{product_max_h:.0f}%.",
                "Check humidity control and packaging seals (condensation/desiccation risk).",
                {"humidity": float(humidity)},
            ))
        battery = getattr(latest_reading, "battery_level", None)
        if battery is not None and float(battery) < float(settings.alert_low_battery_percent):
            items.append(_item(
                "SENSOR_BATTERY_LOW",
                "warning",
                4,
                f"Sensor battery is at {float(battery):.1f}% (below {settings.alert_low_battery_percent:.0f}%).",
                "Replace/charge the sensor battery so monitoring is not interrupted.",
                {"battery_level": float(battery)},
            ))

    recent = list(readings)[-DOOR_OPEN_LOOKBACK_READINGS:]
    recent_door_opens = sum(1 for r in recent if bool(getattr(r, "door_open", False)))
    if recent_door_opens >= DOOR_OPEN_WARN_COUNT and not any(i["code"] == "DOOR_OPEN_NOW" for i in items):
        items.append(_item(
            "FREQUENT_DOOR_OPENING",
            "warning",
            3,
            f"{recent_door_opens} door-open events in the last {len(recent)} readings.",
            "Reduce door-open exposure: review loading/unloading discipline and door seals.",
            {"door_opens": recent_door_opens, "readings_checked": len(recent)},
        ))
    # -------------------------------------------------------- shelf life and ETA
    if shelf_total > 0 and shelf_used_fraction >= SHELF_LIFE_WARN_FRACTION:
        items.append(_item(
            "SHELF_LIFE_CRITICAL",
            "warning",
            2,
            (
                f"{shelf_used_fraction * 100:.0f}% of the shelf life (Q10-equivalent ageing) is used; "
                f"{remaining_shelf:.1f} h remain."
            ),
            "Prioritise shipment handling so the load is delivered/processed before the shelf life runs out.",
            {
                "shelf_life_used_fraction": round(shelf_used_fraction, 4),
                "remaining_shelf_life_hours": remaining_shelf,
            },
        ))

    eta_hours = _hours_until(getattr(shipment, "estimated_arrival_time", None))
    if eta_hours is not None and remaining_shelf > 0 and eta_hours > remaining_shelf:
        items.append(_item(
            "ROUTE_ADJUSTMENT_NEEDED",
            "warning",
            1,
            (
                f"Estimated arrival is in {eta_hours:.1f} h but only {remaining_shelf:.1f} h of shelf life "
                "remain at the current temperature profile."
            ),
            "Consider route adjustment or a nearer delivery point to protect the load.",
            {"hours_to_arrival": round(eta_hours, 2), "remaining_shelf_life_hours": remaining_shelf},
        ))

    if str(getattr(shipment, "status", "")).lower() in ("delayed", "late"):
        items.append(_item(
            "SHIPMENT_DELAYED",
            "info",
            4,
            f"Shipment status is '{shipment.status}'.",
            "Consider route adjustment and confirm the cold chain is still holding.",
            {"status": shipment.status},
        ))

    # ----------------------------------------------------------- fallback rule
    if not items:
        items.append(_item(
            "CONTINUE_MONITORING",
            "info",
            5,
            (
                "All measured conditions are inside the allowed ranges "
                f"({metrics.get('total_readings')} readings, remaining shelf life {remaining_shelf:.1f} h)."
            ),
            "Continue monitoring; no corrective action required.",
            {
                "total_excursion_minutes": excursion_minutes,
                "remaining_shelf_life_hours": remaining_shelf,
                "risk_level": risk_level,
            },
        ))

    items.sort(key=lambda item: (item["priority"], SEVERITY_ORDER.get(item["severity"], 9), item["code"]))
    return items
