"""CNN packaging-condition classifier.

NOTE: no real labeled packaging photos exist yet, so this script can generate
clearly-marked DEMO/SYNTHETIC images for pipeline development. Any accuracy
reported from them is a DEMO metric, not real-world validation.
"""
import argparse
import json
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))

from ml.utils.common import ARTIFACTS, save_json  # noqa: E402

CLASSES = ["ok", "seal_damaged", "insulation_compromised", "wet_condensation", "crushed"]
IMG_DIR = ROOT / "ml" / "data" / "images"
SIZE = 96


def generate_demo_images(n_train=40, n_val=12, root=None):
    """Create clearly-labeled DEMO images (procedural textures, NOT real photos)."""
    from PIL import Image, ImageDraw
    root = Path(root) if root else IMG_DIR
    rng = np.random.default_rng(0)
    looks = {  # class -> (base color, distortion style)
        "ok": ((150, 170, 190), "smooth"),
        "seal_damaged": ((170, 120, 90), "jagged"),
        "insulation_compromised": ((120, 140, 200), "cracks"),
        "wet_condensation": ((90, 130, 160), "droplets"),
        "crushed": ((160, 150, 120), "folds"),
    }
    for split, n in (("train", n_train), ("val", n_val)):
        for cls in CLASSES:
            d = root / split / cls
            d.mkdir(parents=True, exist_ok=True)
            base, style = looks[cls]
            for i in range(n):
                arr = np.clip(np.array(base, float) + rng.normal(0, 12, (SIZE, SIZE, 3)), 0, 255)
                img = Image.fromarray(arr.astype("uint8"))
                dr = ImageDraw.Draw(img)
                if style == "jagged":
                    pts = [(x, SIZE // 2 + int(18 * np.sin(x))) for x in range(0, SIZE, 4)]
                    dr.line(pts, fill=(30, 30, 30), width=4)
                elif style == "cracks":
                    for _ in range(4):
                        dr.line([(rng.integers(SIZE), rng.integers(SIZE))
                                 for _ in range(3)], fill=(20, 20, 20), width=2)
                elif style == "droplets":
                    for _ in range(25):
                        x, y = rng.integers(0, SIZE - 8, 2)
                        dr.ellipse([x, y, x + 7, y + 7], fill=(220, 230, 240))
                elif style == "folds":
                    for y in range(0, SIZE, 16):
                        dr.line([(0, y), (SIZE, y + 8)], fill=(60, 55, 40), width=3)
                img.save(d / f"demo_{cls}_{i:03d}.png")
    (root / "DEMO_DATA.md").write_text(
        "# DEMO / SYNTHETIC IMAGES\n\nGenerated by `ml/training/train_cnn.py --generate-demo`.\n"
        "These are procedural placeholders, NOT real packaging photos.\n"
        "CNN metrics on them are DEMO metrics only - replace with real labeled\n"
        "images under train/<class>/ and val/<class>/ for real validation.\n")
    return root


def preprocess_image(path, size=SIZE):
    """Load one image -> float32 CHW-ready array in [0, 1], resized to size x size."""
    from PIL import Image
    with Image.open(path) as im:
        im = im.convert("RGB").resize((size, size))
        return np.asarray(im, dtype=np.float32) / 255.0


def load_split(root, split, size=SIZE):
    X, y = [], []
    for i, cls in enumerate(CLASSES):
        for p in sorted((root / split / cls).glob("*.png")):
            X.append(preprocess_image(p, size))
            y.append(i)
    return np.asarray(X, np.float32), np.asarray(y, np.int64)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--images", default=str(IMG_DIR))
    ap.add_argument("--epochs", type=int, default=8)
    ap.add_argument("--generate-demo", action="store_true",
                    help="generate DEMO images (only if train dir is empty)")
    args = ap.parse_args()
    root = Path(args.images)

    if not (root / "train" / CLASSES[0]).exists() or args.generate_demo:
        print("[data] generating DEMO/SYNTHETIC images (no real packaging photos yet)")
        generate_demo_images(root=root)

    Xtr, ytr = load_split(root, "train")
    Xva, yva = load_split(root, "val")
    if len(Xtr) == 0:
        raise SystemExit("No images found. Run with --generate-demo or add real images.")
    print(f"[images] train={len(Xtr)} val={len(Xva)} classes={CLASSES}")

    from tensorflow import keras
    model = keras.Sequential([
        keras.layers.Input((SIZE, SIZE, 3)),
        keras.layers.Conv2D(16, 3, activation="relu", padding="same"),
        keras.layers.MaxPooling2D(),
        keras.layers.Conv2D(32, 3, activation="relu", padding="same"),
        keras.layers.MaxPooling2D(),
        keras.layers.Flatten(),
        keras.layers.Dense(64, activation="relu"),
        keras.layers.Dense(len(CLASSES), activation="softmax")])
    model.compile(optimizer="adam", loss="sparse_categorical_crossentropy",
                  metrics=["accuracy"])
    model.fit(Xtr, ytr, validation_data=(Xva, yva), epochs=args.epochs,
              batch_size=32, verbose=2)
    loss, acc = model.evaluate(Xva, yva, verbose=0)
    print(f"[val accuracy] {acc:.3f}  <- DEMO/SYNTHETIC images, NOT real-world validation")

    ARTIFACTS.mkdir(parents=True, exist_ok=True)
    model.save(ARTIFACTS / "cnn_packaging.keras")
    save_json({"classes": CLASSES, "image_size": SIZE, "epochs": args.epochs,
               "val_accuracy": float(acc), "n_train": int(len(Xtr)),
               "n_val": int(len(Xva)), "data_kind": "DEMO/SYNTHETIC images",
               "note": "Replace demo images with real labeled photos for real validation."},
              ARTIFACTS / "cnn_meta.json")
    print(f"saved -> {ARTIFACTS / 'cnn_packaging.keras'} + cnn_meta.json")


if __name__ == "__main__":
    main()
